add Kagoshima 2023
railsgirls/railsgirls.com pull request #2186
Opened 2023-07-10 00:51 UTC by Turu0512

## What I have changed

create kagoshima 2023 page
add kagoshima 2nd logo

2023-07-18 23:57 UTC, Turu0512 commented
![__1 _8000_kagoshima-2023 html](https://github.com/railsgirls/railsgirls.com/assets/84743939/a1a890c8-086e-4680-a894-5aa5d485d649)

2023-07-19 23:29 UTC, emorima requested changes

2023-07-19 23:29 UTC, emorima commented on kagoshima-2023.html
> +        <p>
please add annual sponsors for Rails Girls Japan.  
https://railsgirls.jp/sponsors/

* ENISHI TECH INC.
* TokyoDev
* pixiv
* SMS
* STORES
* FjordBootCamp
* GMOペパボ

2023-07-20 00:54 UTC, Turu0512 commented
![__1 _8000_kagoshima-2023 html (2)](https://github.com/railsgirls/railsgirls.com/assets/84743939/0b8eca9b-9aff-4d70-9572-ebacc64d208a)

2023-07-20 01:07 UTC, emorima approved these changes

2023-07-20 01:07 UTC, merged